properties([
  disableConcurrentBuilds(),
  buildDiscarder(logRotator(numToKeepStr: '8', daysToKeepStr: '20'))
])

try {
  timeout(time: 1, unit: 'HOURS') {
    runPod(image: 'quay.io/pypa/manylinux2014_x86_64') {
      stage('main') {
        withEnv([
          "HOME=${WORKSPACE}",
          "LC_ALL=C"
        ]) {
          sh 'cmake -B build . -DCMAKE_BUILD_TYPE=Release'
          sh 'cd build && make -j4'
          sh 'cd build && ctest --output-on-failure'
        }
      }
    }
  }
}
finally {
  emailFailure()
}
